"""SyKaşif çekirdek sabitleri."""

from __future__ import annotations

SCHEMA_VERSION = "1.0.0"

DEFAULT_COORDINATE_SYSTEM = "EPSG:4326"
DEFAULT_SEARCH_RADIUS_METERS = 100.0

MIN_LATITUDE = -90.0
MAX_LATITUDE = 90.0
MIN_LONGITUDE = -180.0
MAX_LONGITUDE = 180.0

MIN_SEARCH_RADIUS_METERS = 0.1
MAX_SEARCH_RADIUS_METERS = 100_000.0

MIN_ACCURACY_METERS = 0.0
MAX_ACCURACY_METERS = 100_000.0

SYK_IDENTIFIER_PREFIX = "SYK"
RESEARCH_POINT_PREFIX = "RP"
LAYER_PREFIX = "LYR"
EVIDENCE_PREFIX = "EVD"

HASH_ALGORITHM = "sha256"
